
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar, SidebarSection, SidebarItem, SidebarFolder } from '@/components/sidebar';
import localFont from 'next/font/local';
import { Menu, X } from "lucide-react";

const arimo = localFont({
  src: [
    {
      path: '../public/fonts/Arimo/static/Arimo-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/Arimo/static/Arimo-Bold.ttf'
    },
    {
      path: '../public/fonts/Arimo/Arimo-VariableFont_wght.ttf'
    }
  ],
  variable: '--font-arimo',
});

const publicSans = localFont({
  src: [
    {
      path: '../public/fonts/Public_Sans/static/PublicSans-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-public-sans',
})

import ClientLayout from "@/components/pages/ClientLayout";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className="dark ">
      <body className={`${geistSans.variable} ${arimo.variable} ${geistMono.variable} ${publicSans.variable} antialiased text-white`}>
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}